lib/languager_web/router.ex
defmodule LanguagerWeb.Router do
  use LanguagerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LanguagerWeb.Plugs.LoadCurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", LanguagerWeb do
    pipe_through :api

    scope "/v1" do 
      scope "/sessions" do
        post "/signin", SessionController, :create
        delete "/signout", SessionController, :delete
      end

      resources "/languages", LanguageController, except: [:new, :edit]
    end
  end

  scope "/", LanguagerWeb do
    pipe_through :browser

    # get "/logout", SessionController, :delete
    # get "/signout", SessionController, :delete
    # get "/login", SessionController, :new
    # get "/signin", SessionController, :new
    # resources "/sessions", SessionController, only: [:new, :create, :delete]

    # get "/signup", SignupController, :new
    # post "/signup", SignupController, :create

    # get "/", PageController, :index
    get "/*path", PageController, :index
  end
end

lib/languager_web/controllers/session_controller.ex
defmodule LanguagerWeb.SessionController do
  use LanguagerWeb, :controller
  alias Languager.Accounts.User
  plug LanguagerWeb.Plugs.RequireLoggedIn when action in [:delete]
  # plug LanguagerWeb.Plugs.RequireNotLoggedIn when action not in [:delete]


  # curl http://localhost:4000/api/v1/sessions/signin -H "Content-Type: application/json" -d '{ "email":"test@example.com", "password": "123123" }' -X POST
  def create(conn, %{"email" => ""}), do: missing_fields(conn)
  def create(conn, %{"password" => ""}), do: missing_fields(conn)
  def create(conn, %{"email" => email, "password" => password}) do
    case verify_credentials(email, password) do
      {:ok, user, token} ->
        conn
        |> put_status(:ok)
        |> render("show.json", %{user: user, token: token})
      {:error, _reason} ->
        conn
        |> put_status(401)
        |> put_view(LanguagerWeb.ErrorView)
        |> render("error.json", %{message: gettext("Invalid email or password.")})
    end
  end
  def create(conn, _params), do: missing_fields(conn)
  defp missing_fields(conn) do
    conn
    |> put_status(401)
    |> put_view(LanguagerWeb.ErrorView)
    |> render("error.json", %{message: gettext("Please fill in an email and password.")})
  end

  def delete(conn, _params) do
    Languager.Services.Authenticator.delete_token(conn)
    conn
    |> send_resp(204, "")
  end


  defp verify_credentials(email, password) when is_binary(email) and is_binary(password) do
    with {:ok, user} <- find_by_email(email),
      do: verify_password(password, user)
  end

  defp find_by_email(email) when is_binary(email) do
    case Languager.Repo.get_by(User, email: email) do
      nil ->
        Argon2.no_user_verify()
        {:error, gettext("User with email '%{name}' not found", name: email)}
      user ->
        {:ok, user}
    end
  end

  defp verify_password(password, %User{} = user) when is_binary(password) do
    if Argon2.verify_pass(password, user.encrypted_password) do
      token = Languager.Services.Authenticator.generate_token(user.id)
      Languager.Repo.insert(Ecto.build_assoc(user, :auth_tokens, %{token: token}))
      {:ok, user, token}
    else
      {:error, :invalid_password}
    end
  end
end

lib/languager_web/views/session_view.ex
defmodule LanguagerWeb.SessionView do
  use LanguagerWeb, :view

  def render("show.json", %{user: user, token: token}) do
    %{data: %{token: token, email: user.email, name: user.name, external_id: user.external_id}}
  end
end

lib/languager_web/templates/session/new.html.eex
<div class="mx-auto max-w-sm">
    <div class="py-10 text-center">
        @include('logo', ['style' => 'max-width: 12rem;'])
    </div>

    <div class="bg-white rounded shadow">
        <div class="border-b py-8 font-bold text-black text-center text-xl tracking-widest uppercase">
            Welcome back!
        </div>

        <%= form_for @conn, Routes.session_path(@conn, :create), [as: :session, class: "bg-grey-lightest px-10 py-10"], fn f -> %>
            <div class="mb-3">
              <%= if assigns[:error_message] do %>
                <div class="text-danger">
                  <p><%= @error_message %></p>
                </div>
              <% end %>
            </div>

            <div class="mb-3">
                <%= text_input f, :email, class: "border w-full p-3 focus:outline-none focus:bg-white focus:border-gray-500", placeholder: gettext("Email") %>
                <%= error_tag f, :email %>
            </div>
            <div class="mb-6">
                <%= password_input f, :password, class: "border w-full p-3 focus:outline-none focus:bg-white focus:border-gray-500", placeholder: "**************" %>
                <%= error_tag f, :password %>
            </div>
            <div class="flex">

                <button class="bg-primary hover:bg-primary-dark w-full p-4 text-sm text-white uppercase font-bold tracking-wider">
                    <%= gettext("Login") %>
                </button>
            </div>
        <% end %>

        <div class="border-t px-10 py-6">
            <div class="flex justify-between">
                <a href="/signup" class="font-bold text-primary hover:text-primary-dark no-underline"><%= gettext("Don't have an account?") %></a>
                <a href="#" class="text-grey-darkest hover:text-black no-underline"><%= gettext("Forgot Password?") %></a>
            </div>
        </div>
    </div>
</div>